source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'../'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    #pod 'ATSDK-Weex', '0.0.1'
end

target 'weexSDK_Example' do
    common
end

target 'weexSDK_Tests' do
    common
end
